import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface AssetMeta {
  id: string;
  type: 'product' | 'logo';
  url: string;
  width?: number;
  height?: number;
}

interface GenerateRequest {
  adId: string;
  sizeSpec: { width: number; height: number };
  dpi: number;
  bleedPx: number;
  safePx: number;
  minFontSize: number;
  copy: string;
  brief: string;
  assets: AssetMeta[];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { adId, sizeSpec, dpi, bleedPx, safePx, minFontSize, copy, brief, assets }: GenerateRequest = await req.json();

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Build the image generation prompt
    const aspectRatio = sizeSpec.width > sizeSpec.height ? "landscape" : 
                        sizeSpec.width < sizeSpec.height ? "portrait" : "square";
    
    // Get asset URLs for the prompt
    const productAssets = assets.filter(a => a.type === 'product');
    const logoAssets = assets.filter(a => a.type === 'logo');

    const imagePrompt = `Create a professional print classified advertisement with these specifications:

**Ad Size:** ${sizeSpec.width}x${sizeSpec.height} pixels (${aspectRatio} orientation)
**Print specs:** ${dpi} DPI, ${bleedPx}px bleed, ${safePx}px safe margin

**Creative Brief:**
${brief || "Professional classified ad layout"}

**Ad Copy (must appear legibly in the ad):**
${copy || "Contact us for more information"}

**Design Requirements:**
- Clean, professional classified ad style suitable for newspaper/magazine print
- Text must be large and highly readable (minimum ${minFontSize}pt equivalent)
- Keep important content within safe margins
- High contrast for print reproduction
- Include clear visual hierarchy: headline, body text, contact info
${productAssets.length > 0 ? `- Feature the product prominently` : ''}
${logoAssets.length > 0 ? `- Include logo placement` : ''}

Generate a complete, print-ready classified advertisement image.`;

    console.log("Generating ad image for:", { adId, sizeSpec, brief: brief?.substring(0, 50) });

    // Build message content - include asset images if available
    const messageContent: any[] = [{ type: "text", text: imagePrompt }];
    
    // Add product and logo images to the prompt for better context
    for (const asset of assets.slice(0, 2)) { // Limit to 2 images
      if (asset.url) {
        messageContent.push({
          type: "image_url",
          image_url: { url: asset.url }
        });
      }
    }

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          { 
            role: "user", 
            content: messageContent
          }
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI credits exhausted. Please add credits to continue." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      return new Response(
        JSON.stringify({ error: "AI generation failed" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const data = await response.json();
    console.log("AI response received");

    // Extract the generated image
    const message = data.choices?.[0]?.message;
    const generatedImage = message?.images?.[0]?.image_url?.url;
    const aiDescription = message?.content || "";

    if (!generatedImage) {
      console.error("No image in response:", JSON.stringify(data));
      throw new Error("No image generated by AI");
    }

    // Convert base64 to blob and upload to storage
    const base64Data = generatedImage.replace(/^data:image\/\w+;base64,/, '');
    const imageBytes = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
    
    const fileName = `generated/${adId}/${Date.now()}.png`;
    const { error: uploadError } = await supabase.storage
      .from('ad-assets')
      .upload(fileName, imageBytes, {
        contentType: 'image/png',
        upsert: true
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw new Error("Failed to save generated image");
    }

    // Get public URL
    const { data: urlData } = supabase.storage
      .from('ad-assets')
      .getPublicUrl(fileName);

    const imageUrl = urlData.publicUrl;
    console.log("Image uploaded:", imageUrl);

    // Create a version entry with the generated image
    const { error: versionError } = await supabase
      .from('versions')
      .insert({
        ad_id: adId,
        source: 'ai',
        layout_json: {
          document: { widthPx: sizeSpec.width, heightPx: sizeSpec.height, dpi, bleedPx, safePx },
          elements: [],
          metadata: { 
            templateName: "AI Generated Ad",
            rationale: aiDescription,
            warnings: []
          }
        },
        preview_url: imageUrl,
        is_selected: true
      });

    if (versionError) {
      console.error("Version insert error:", versionError);
    }

    // Deselect other versions
    await supabase
      .from('versions')
      .update({ is_selected: false })
      .eq('ad_id', adId)
      .neq('preview_url', imageUrl);

    return new Response(
      JSON.stringify({ 
        success: true,
        imageUrl,
        description: aiDescription
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("generate-layouts error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
